### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by evanraalte** [Miksus/rocketry#221]
**Describe the bug**
I'm trying to run the example described [here](https://rocketry.readthedocs.io/en/stable/cookbook/testing.html#tasks). 

It seems that the `do_things` function is not executed, when running the example

The expected behaviour is 

**To Reproduce**
I modified the example a bit, so that files are touched and hence I can verify that the function `do_things` is run correctly.

main.py:
```python
from rocketry import Rocketry
from pathlib import Path
app = Rocketry()

@app.task()
def do_things():
    Path("getting_here").touch()
if __name__ == "__main__":
    Path("getting_here_too").touch()
    app.session.run(do_things)
```

pyproject.toml:
```toml
[tool.poetry]
name = "rocketry_playground"
version = "0.1.0"
description = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
rocketry = "^2.5.1"
pydantic = "^1.10"
sqlalchemy = "1.4.41"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Run: 
```bash
poetry install
poetry run python main.py
```

**Expected behavior**
I expect there to be two files added after the script runs:
- `getting_here_too` generated in the main loop
- `getting_here` generated in the do_things function

**Actual behavior**

<img width="546" alt="image" src="https://github.com/Miksus/rocketry/assets/11211570/3a55da67-1a58-4683-873a-c787ea9a946b">

(note that the `getting_here` file is not generated.
